# Generated by Django 3.1.5 on 2021-12-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Motorcycle', 'Motorcycle'), ('Car', 'Car')], default='Motorcycle', max_length=50)),
                ('price', models.IntegerField()),
                ('desription', models.TextField()),
                ('duration', models.DurationField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Client', 'Client')], default='Client', max_length=50),
        ),
    ]
