# Generated by Django 3.1.5 on 2021-12-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20211208_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
