# Generated by Django 3.1.5 on 2021-12-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20211209_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='slot',
            field=models.CharField(choices=[('Slot 1', 'Slot 1'), ('Slot 2', 'Slot 2'), ('Slot 3', 'Slot 3')], default='Slot 1', max_length=10),
        ),
    ]
