# Generated by Django 3.1.5 on 2021-12-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_inquiriesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiriesmodel',
            name='email',
            field=models.EmailField(max_length=55),
        ),
    ]
