# Generated by Django 3.1.5 on 2021-12-10 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkinInvoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('Slot 1', 'Slot 1'), ('Slot 2', 'Slot 2'), ('Slot 3', 'Slot 3')], default='Slot 1', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_wim_service', to='booking.servicesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceBookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('Slot 1', 'Slot 1'), ('Slot 2', 'Slot 2'), ('Slot 3', 'Slot 3')], default='Slot 1', max_length=10)),
                ('time_slot', models.CharField(choices=[('1', '8:00am - 10:00am'), ('2', '10:00am - 12:00pm'), ('3', '12:00pm- 2:00pm'), ('4', '2:00pm - 4:00pm'), ('5', '4:00pm - 6:00pm'), ('6', '6:00pm - 8:00pm')], default='1', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ibm_service', to='booking.servicesmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ibm_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
