# Generated by Django 3.1.5 on 2021-12-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20211210_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkininvoicemodel',
            name='slot',
            field=models.CharField(choices=[('Slot 1', 'Slot 1'), ('Slot 2', 'Slot 2'), ('Slot 3', 'Slot 3'), ('Slot 4', 'Slot 4'), ('Slot 5', 'Slot 5'), ('Slot 6', 'Slot 6')], default='Slot 1', max_length=10),
        ),
    ]
