# Generated by Django 3.2 on 2021-12-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20211210_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiriesmodel',
            name='f_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiriesmodel',
            name='l_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiriesmodel',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
