# Generated by Django 3.2.9 on 2021-12-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20211211_1631'),
        ('booking', '0015_auto_20211211_1633'),
    ]

    operations = [
    ]
